name: Feature Branch - Docker Build

on:
  pull_request:
    branches:
      - 'develop'
  push:
    tags:
      - '*'
  
 
permissions:
  packages: write
    
jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set lower case Github repository name
        run: |
          echo "GH_REPO_LC=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set proper tag name for Docker image
        run: |
          # Extracting the substring after "refs/heads/"
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"

          # Converting to lower case and replacing '/' with '-'
          BRANCH_NAME_LOWER=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]' | sed 's|/|-|g')

          # Creating new environment variable
          echo "TAG_NAME=$BRANCH_NAME_LOWER" >> $GITHUB_ENV

        env:
          GITHUB_REF: ${{ github.ref_name }}

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ env.GH_REPO_LC }}:${{ env.TAG_NAME }}
  
  secure_scan:
    runs-on: ubuntu-latest
    needs: build_docker
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Set lower case Github repository name
        run: |
          echo "GH_REPO_LC=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          
      - name: Set proper tag name for Docker image
        run: |
          # Extracting the substring after "refs/heads/"
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"

          # Converting to lower case and replacing '/' with '-'
          BRANCH_NAME_LOWER=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]' | sed 's|/|-|g')

          # Creating new environment variable
          echo "TAG_NAME=$BRANCH_NAME_LOWER" >> $GITHUB_ENV

        env:
          GITHUB_REF: ${{ github.ref_name }}

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ env.GH_REPO_LC }}:${{ github.TAG_NAME }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
        env:
          TRIVY_USERNAME: ${{ github.actor }}
          TRIVY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
   