name: Docker

on:
  push:
    branches:
      - main
      - github-actions-ci-cd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: set lower case Github repository name
      run: |
        echo "GH_REPO_LC=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      env:
        GITHUB_REPOSITORY: '${{ github.repository }}'

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}


    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/${{ env.GH_REPO_LC }}:${{ github.sha }}
